# Generated by Django 5.2.17 on 2026-10-02 17:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(default='RouteLog HOS', max_length=60)),
                ('workspace_name', models.CharField(default='Demo Transport', max_length=60)),
                ('workspace_subtitle', models.CharField(blank=True, default='Fleet workspace', max_length=60)),
                ('logo', models.ImageField(blank=True, upload_to=accounts.models.logo_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='one_workspace_settings')],
            },
        ),
    ]
